name: cellseg_environment

dependencies:
- python=2.7
- numpy=1.11.1
- pandas=0.18.1
- scikit-image=0.12.3
- scipy=0.18.0
- matplotlib=1.5.1
- seaborn=0.7.1
- ipython=4.0.0

- https://conda.binstar.org/menpo::opencv3=3.1.0=py27_0

- pip:
  - mahotas==1.4.0
 

